- name: Provision with Ansible
  hosts: all
  become: yes
  vars:
    - agent_hostname: zabbix-vm2
    - zabbix_server_ip: 192.168.33.10
  
  tasks:

    # - name: upgrade all packages
    #   yum: name=* state=latest

    - debug: msg="Vm provision with zabbix-agent"

    - name: add a new string at the end of the file
      lineinfile: dest=/etc/hosts
                  regexp=''
                  insertafter=EOF
                  line='192.168.33.10    zabbix-server'

    - name: install zabbix repo
      yum: 
        name: http://repo.zabbix.com/zabbix/2.4/rhel/6/x86_64/zabbix-release-2.4-1.el6.noarch.rpm 
        state: present

    - name: install zabbix-agent and httpd
      yum: >
        name="{{ item }}"
        state=present
      with_items:
        - httpd
        - zabbix-agent

    - name: start httpd
      service: name=httpd state=started enabled=yes

    - name: register eth1 ip address
      shell:
        "ifconfig eth1 | grep 'inet addr:' | cut -d: -f2 | awk '{ print $1}'"
      register: eth1_ip   

    - name: configure zabbix agent
      template: src=zabbix_agentd_conf dest=/etc/zabbix/zabbix_agentd.conf

    - name: configure zabbix agent
      template: 
        src: zabbix_agentd_conf 
        dest: /etc/zabbix/zabbix_agentd.conf  
          
    - name: start zabbix-agent
      service: name=zabbix-agent state=started enabled=yes
