# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure(2) do |config|

#config.vm.provision "shell", inline: "echo Apache_server_install && yum update -y && yum install -y httpd && chkconfig httpd on && /etc/init.d/httpd start"

# $script = <<SCRIPT
# echo Provisioning...
# echo "192.168.33.10    zabbix-server" >> /etc/hosts
# SCRIPT

# config.vm.provision "shell", inline:$script  # provisioning

config.vm.provision "ansible" do |ansible|
   ansible.playbook = 'provision_vm2.yml'
   ansible.verbose = 'vv'
   end

config.vm.define :vm2 do |vm2|
    vm2.vm.box = "sbeliakou/centos-6.7-x86_64"
    vm2.vm.hostname = "zabbix-vm2"
    vm2.vm.network "private_network", ip: "192.168.33.12"
    #vm2.vm.network "forwarded_port", guest: 80, host: 8181
    #vm2.vm.synced_folder ".", "/vagrant", disabled: true
    #vm2.vm.synced_folder "/root/vagrant/share2", "/vagrant-vm-share", owner: "root", group: "root"
    	vm2.vm.provider "virtualbox" do |vb2|
		vb2.name = "zabbix-vm2"
		vb2.customize ["modifyvm", :id, "--memory", 1024]
		#vb2.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
        end
   end
end
