- name: Provision with Ansible
  hosts: all
  become: yes
  
  tasks:

    - name: upgrade all packages
      yum: name=* state=latest

    - name: Install mysql server
      yum: >
        name="{{ item }}"
        state=present
      with_items:
        - mysql
        - mysql-server
        - MySQL-python

    - name: Mysql Initial configuration 
      command: /usr/bin/mysql_install_db --user=mysql

    - name: Edit_my.cnf
      template: src=my_cnf dest=/etc/my.cnf

    - service: name=mysqld state=started enabled=yes

    - name: install zabbix repo
      yum: 
        name: http://repo.zabbix.com/zabbix/2.4/rhel/6/x86_64/zabbix-release-2.4-1.el6.noarch.rpm 
        state: present

    - name: Install zabbix-server and zabbix-agent
      yum: >
        name="{{ item }}"
        state=latest
      with_items: '{{ zabbix_list }}'

    - name: Create DB zabbix
      mysql_db:
        name: zabbix
        encoding: utf8
        collation: utf8_bin
        state: present
    
    - name: Create user zabbix
      mysql_user: name=zabbix password=zabbix priv=zabbix.*:ALL,GRANT state=present

    - name: 
      shell: mysql -uroot zabbix < {{ item }}
      with_items:
        - schema.sql
        - images.sql
        - data.sql
      args:
        chdir: /usr/share/doc/zabbix-server-mysql-2.4.7/create/

    - name: Configure zabbix web prefix
      template: src=zabbix_conf dest=/etc/httpd/conf.d/zabbix.conf

    - name: Configure zabbix server
      template: src=zabbix_server_conf dest=/etc/zabbix/zabbix_server.conf

    - name: Start zabbix-server
      service: name=zabbix-server state=started enabled=yes

    - name: Start httpd
      service: name=httpd state=started enabled=yes