---
# tasks file for java
- debug: msg="Will download and install JDK 7 files"

- name: Setup working directory
  file: path=/tmp/install state=directory
    
- name: OpenJDK install
  yum: name=java-1.7.0-openjdk state=latest
    
- name: Check JDK 7 dir
  stat: path=/opt/jdk1.7.0_79/
  register: jdk7_dir
    
- name: Download JDK 7
  get_url:
    url: http://download.oracle.com/otn-pub/java/jdk/7u79-b15/jdk-7u79-linux-x64.tar.gz
    dest: /tmp/install
    headers: "Cookie: gpw_e24=http%3A%2F%2Fwww.oracle.com%2F; oraclelicense=accept-securebackup-cookie"
  register: jdk7_targz
  when: jdk7_dir.stat.exists == False

- name: Extract JDK 7 archive
  unarchive: src=/tmp/install/jdk-7u79-linux-x64.tar.gz dest=/opt/ copy=no creates=/opt/jdk1.7.0_79/
  when: jdk7_dir.stat.exists == False

- name: Java is installed in alternatives
  alternatives: name=java link=/usr/bin/java path=/opt/jdk1.7.0_79/bin/java
