- name: Provision with Ansible
  hosts: all
  become: yes
  vars: 
   - agent_hostname: zabbix-vm3
   - zabbix_server_ip: 192.168.33.10
   - host_group_id: 2
   - zabbix_username: Admin
   - zabbix_password: zabbix
   - template_id: 10108
   - url: http://zabbix-server/api_jsonrpc.php

  tasks:

    - debug: msg="Vm provision with zabbix-agent"

    - name: add a new string at the end of the file
      lineinfile: dest=/etc/hosts
                  regexp=''
                  insertafter=EOF
                  line='192.168.33.10     zabbix-server'

    - name: install zabbix repo
      yum: 
        name: http://repo.zabbix.com/zabbix/2.4/rhel/6/x86_64/zabbix-release-2.4-1.el6.noarch.rpm 
        state: present

    - name: install zabbix-agent and httpd
      yum: >
        name="{{ item }}"
        state=present
      with_items:
        - telnet
        - zabbix-agent
        - python-requests
        - httpd

    - file: path=/var/log/httpd mode=0755

    - name: register eth1 ip address
      shell:
        "ifconfig eth1 | grep 'inet addr:' | cut -d: -f2 | awk '{ print $1}'"
      register: eth1_ip   

    - name: configure zabbix agent
      template: src=zabbix_agentd_conf dest=/etc/zabbix/zabbix_agentd.conf

    - name: copy python script
      copy: src=zabbix_agent_setup_py dest=/tmp/zabbix.py owner=vagrant group=vagrant mode=0744

    - name: register zabbix-agent on server
      command: /tmp/zabbix.py {{ agent_hostname }} {{ eth1_ip.stdout }} {{ host_group_id }} {{ zabbix_username }} {{ zabbix_password }} {{ template_id }} {{ url }}
          
    - name: start and enable zabbix-agent
      service: name={{ item }} state=started enabled=yes
      with_items:
         - httpd
         - zabbix-agent
