# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure(2) do |config|

#config.vm.provision "shell", inline: "echo Apache_server_install && yum update -y && yum install -y httpd && chkconfig httpd on && /etc/init.d/httpd start"

# $script = <<SCRIPT
# echo Provisioning...
# echo "192.168.33.10    zabbix-server" >> /etc/hosts
# SCRIPT

# config.vm.provision "shell", inline:$script  # provisioning

config.vm.provision "ansible" do |ansible|
   ansible.playbook = 'provision_vm3.yml'
   ansible.verbose = 'vv'
   end

config.vm.define :vm3 do |vm3|
    vm3.vm.box = "sbeliakou/centos-6.7-x86_64"
    vm3.vm.hostname = "zabbix-vm3"
    vm3.vm.network "private_network", ip: "192.168.33.13"
    #vm3.vm.network "forwarded_port", guest: 80, host: 8181
    #vm3.vm.synced_folder ".", "/vagrant", disabled: true
    #vm3.vm.synced_folder "/root/vagrant/share2", "/vagrant-vm-share", owner: "root", group: "root"
    	vm3.vm.provider "virtualbox" do |vb3|
		vb3.name = "zabbix-vm3"
		vb3.customize ["modifyvm", :id, "--memory", 1024]
		#vb3.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
        end
   end
end
